#Ce fichier contiens la config de base du serveur---
installation: true
licence: free-craftmywebsite.fr
General:
    url: http://localhost/CMW/
    name: Test Teyir
    theme: default
    themeOption: bootstrap
    description: Site de dev CMW pour Teyir
    bgType: 0
    permsPlugin: groupManager
    permsWorld: world
    ipTexte: mc.one-dream.fr
    ip: 127.0.0.1
    port: "25565"
    statut: 2
    moneyName: Jeton
    createur:
        nom: Créateur
        effets: style16
        couleur: '#ffffff'
        bg: '#b83d3d'
    joueur: Joueur
DataBase:
    dbAdress: localhost
    dbName: cmw
    dbUser: root
    dbPassword: ""
    dbPort: "3306"
Payement:
    paypal: true
    dedipass: false
    paysafecard: false
    currency: EUR
    public_key: ""
    private_key: ""
    paypalEmail: ""
vote:
    maxDisplay: 10
color:
    panel:
        main: '#ff8040'
        hover: '#c16100'
        focus: '#ffbc9b'
lastCMWCheck: 1649689461
googleService:
    searchConsole:
        id: ""
        enable: false
    analytics:
        enable: false
        id: ""
    adsense:
        enable: false
        id: ""
        pub: ""
